configure :development do
  set :database, {adapter: 'postgresql',  encoding: 'UTF-8', database: 'data.db', pool: 2, username: 'Yuriy', password: '1234'}
end

configure :production do
  set :database, {adapter: 'postgresql',  encoding: 'UTF-8', database: 'data.db', pool: 2, username: 'Yuriy', password: '1234'}
end